pipeline:
  web-modeler-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t borders-workflow-modeler .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+borders_central" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag borders-workflow-modeler quay.io/ukhomeofficedigital/borders-workflow-modeler:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/borders-workflow-modeler:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:latest
    commands:
       - scripts/deploy.sh
    secrets:
      - kube_token_dev
    when:
      event: deployment