---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: borders-workflow-modeler
spec:
  replicas: {{ .MODELER_REPLICAS }}
  template:
    metadata:
      labels:
        name: borders-workflow-modeler
    spec:
      containers:
      - name: borders-workflow-modeler
        image: quay.io/ukhomeofficedigital/borders-workflow-modeler:$${DRONE_COMMIT_SHA}
        ports:
          - name: http
            containerPort: 8080
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443