---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: permit-ingress
spec:
  podSelector:
    matchLabels:
      name: borders-workflow-modeler
  ingress:
    - ports:
      - protocol: TCP
        port: 443