apiVersion: v1
kind: Service
metadata:
  labels:
    name: borders-workflow-modeler
  name: borders-workflow-modeler
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: borders-workflow-modeler