apiVersion: v1
kind: Service
metadata:
  labels:
    name: workflow-web-modeler
  name: workflow-web-modeler
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: workflow-web-modeler